### ISSUE TITLE
Dark scannerimage

### ISSUE THREAD

**Issue by SolutionSoftwareMaexx** [JimmyPun610/BarcodeScanner.XF#101]
Hello,
I use BarcodeScanner.FX in my app. It always worked very well too. 
Since about 3 weeks the scanner image is much too dark.
In the simulator it works. But on my POCO X3 nfc comes the problem.
The example app works fine though.
Is another update or another nuget package responsible for this? 
The last thing I installed was Xamarin.FFimageLoading.Forms. Have also tried it without.
I don't know what else I could check.
RequestFPS has no influence at all.
Greetings Marcel

**Comment by JimmyPun610** [comment]
Hi @SolutionSoftwareMaexx,

I do not think it is related to Xamarin.FFImageLoading.Forms, what is the exact problem are you facing?

**Comment by davidjonsson** [comment]
I have this as well on 6.2.0-pre on Android (have not tried iOS yet). The camera feed is almost completely dark. If I point the camera into a light I can see it just barely

**Comment by JimmyPun610** [comment]
Hi @davidjonsson ,

I only got a Pixel 3 and it is not happening.
About RequestFPS, it is for Android only, and it only set on demand. 
https://github.com/JimmyPun610/BarcodeScanner.XF/blob/8e961c0faeecad7fdb92b3a0201f501424bee934/GoogleVisionBarCodeScanner/Android/Renderer/CameraViewRenderer.cs#L92-L99

**Comment by mantasdaskev** [comment]
Hi, I have a same problem with a latest nuget. I am debugging on Xiaomi 11T (Android 12) and Lenovo Yoga Tab 11 (Android 11) tablet. Preview on both devices are very dimmed.

**Comment by AlessandroLanzoni** [comment]
I have the same problem, I use a Redmi 8 Pro for testing.  And same of mantasdaskev, if I remove RequestedFPS image is normal

**Comment by markuznw** [comment]
Same problem here on Realme RMX3363, same fix (removing RequestedFPS)

**Comment by JimmyPun610** [comment]
RequestFPS is required to set only if you have that needs.
