### ISSUE TITLE
Running as Fragment

### ISSUE THREAD

**Issue by wacki4** [JimmyPun610/BarcodeScanner.XF#106]
Is it possible to run BarcodeScanner.XF on android as fragment?
I would like to make a fragment class which would initialize scanner - and it will be replaced and shown on existing fragment. I didn't found any example on such use, and don't know how to set manually SurfaceView on which it should be seen - or is it even possible to done.

**Comment by JimmyPun610** [comment]
Hi @wacki4,

The library is for Xamarin Form. 
I think you could take some native development code sample for your reference (if any) for Xamarin Android
