### ISSUE TITLE
SampleApp: Missing camera permissions

### ISSUE THREAD

**Issue by TedStryker** [JimmyPun610/BarcodeScanner.XF#11]
Since Android 6 any app needs runtime permissions.
(see: https://stackoverflow.com/questions/26305107/how-to-fix-fail-to-connect-to-camera-service-exception-in-android-emulator)

In the SampleApp it was missing and the app failed to connect to the camera service.
I added in MainActivity.OnCreate:

```
            var permission = Android.Support.V4.Content.ContextCompat.CheckSelfPermission(this, Manifest.Permission.Camera);
            if (permission != Android.Content.PM.Permission.Granted)
            {
                Android.Support.V4.App.ActivityCompat.RequestPermissions(this, new string[] { Android.Manifest.Permission.Camera }, 50);
            }
```

But that is just a quick hack to get the SampleApp up and running.

**Comment by christophedemey** [comment]
HI @TedStryker thanks for saving my day ;) this resolved my issue.

**Comment by JimmyPun610** [comment]
@TedStryker 
Updated to version 4.2.1. New method
```
bool allowed = await GoogleVisionBarCodeScanner.Methods.AskForRequiredPermission();
```

You can use this method to request for permission in your xamarin form project.
You will need Plugin.Permission and Plugin.CurrentActivity to do this, please refer to the sample / readme.md
