### ISSUE TITLE
Does this library requires NSPhotoLibraryUsageDescription?

### ISSUE THREAD

**Issue by brunonocetti** [JimmyPun610/BarcodeScanner.XF#110]
While sending an app using this library to the App Store I'm getting "Missing Purpose String in Info.plist ... NSPhotoLibraryUsageDescription". I'm positive that I'm not using any API that requires this permission, so I'm going through 3rd party libraries 1 by 1 checking if it requires this permission.

**Comment by JimmyPun610** [comment]
There is a function to do the image recognition for image from photo library. Not sure if you need to add it even you are not using it in your app.
