### ISSUE TITLE
CameraView.CameraFacing  property does not exist.

### ISSUE THREAD

**Issue by Dinesh2411** [JimmyPun610/BarcodeScanner.XF#113]
Hi Jimmy,

I am using BarcodeScanner.XF library for scanning the QR Codes which is working absolutely fine with the Back camera of the device. But my requirement is to scan the QR Codes with the Front camera of the device. 

As per the documentation [here](https://github.com/JimmyPun610/BarcodeScanner.XF) , there must be CameraFacing property to switch from Back to Front Camera which doesn't exist.

Just want to know how can i use the front camera for scanning.

I am using the **5.0.9** version of the library.

Thanks in advance.

**Comment by JimmyPun610** [comment]
please try 6.2.2-pre

**Comment by Dinesh2411** [comment]
Great Thanks a lot.
