### ISSUE TITLE
Debug SampleApp.Android error

### ISSUE THREAD

**Issue by christophedemey** [JimmyPun610/BarcodeScanner.XF#14]
Hi, i cloned the repo and when trying to debug the SampleApp.Android i get following error :
Java.Lang.RuntimeException: 'Fail to connect to camera service'

Any ideas?

Thanks!

**Comment by christophedemey** [comment]
Got it again... error in output was more helpfull...
```
Java.Lang.RuntimeException: 'Fail to connect to camera service'
```
Fixed by adding this in oncreate
```
            var permission = Android.Support.V4.Content.ContextCompat.CheckSelfPermission(this, Android.Manifest.Permission.Camera);
            if (permission != Android.Content.PM.Permission.Granted)
            {
                Android.Support.V4.App.ActivityCompat.RequestPermissions(this, new string[] { Android.Manifest.Permission.Camera }, 50);
            }
```

**Comment by JimmyPun610** [comment]
Required Camera Permission on Android. Close the issue

**Comment by christophedemey** [comment]
Hi @JimmyPun610 

Can we add this to the introduction page with getting started quickly steps?

**Comment by JimmyPun610** [comment]
> Hi @JimmyPun610
> 
> Can we add this to the introduction page with getting started quickly steps?

Hi, I'm making a update on it. Will have a function call on permission request

**Comment by JimmyPun610** [comment]
@christophedemey 
AskForRequiredPermission methods added.
You will need to install both Plugin.Permission and Plugin.CurrentActivity to do it.
Please look for sample for demonstration
