### ISSUE TITLE
Multiple scans

### ISSUE THREAD

**Issue by alexnavarrova** [JimmyPun610/BarcodeScanner.XF#16]
I am trying to scan more than once, I mean if I have setted a parameter, the app will allow or not to scan another code, the functionality would be similar to a picking system.

It would be nice the libabry would allow multiple scans

**Comment by JimmyPun610** [comment]
Hi @alexnavarrova 
Do you mean do not dispose the scanning page and allow continues scanning?
Since MLKit Barcode Scanning have supported multiple scan on one time already.

**Comment by alexnavarrova** [comment]
yes,  I think there should be a property to set it

**Comment by JimmyPun610** [comment]
I will investigate on it when i am free.

**Comment by JimmyPun610** [comment]
Hi @alexnavarrova 
I made some changes on the source. You may get this feature on 4.2.1.3 by below approach.
1. Do not dispose your scanning page after onDetected event fired on your program
2. Do you work on the event
3. Fire GoogleVisionBarCodeScanner.Methods.Reset() to make the camera start scanning again.
4. Go back to 1.

There is a working example in the sample program.

**Comment by alexnavarrova** [comment]
I proved your changes and they were successful. Thanks for the collaboration
