### ISSUE TITLE
Enable/Disable scanning by App

### ISSUE THREAD

**Issue by TedStryker** [JimmyPun610/BarcodeScanner.XF#18]
I would very much like to have the possibility to start my App with the CameraView visible but scanning being disabled and later enabled on some UI interaction like tapping and disabled again.

Use case:
Think of an App scanning tickets. At the moment, when you display the CameraView and by chance some arbitrary barcode(s) is (are) seen by the phone's camera: it will immediately be scanned and some business processes will start...
I would propose to change GoogleVisionBarCodeScanner.Methods.Reset to .Enable and .Disable instead.
This way it would also be possible to hide the cameraview to save some battery power, enable it again w/o immediately scanning some barcodes lying around, tapping the display and then scan.

My workaround isn't too nice: disabling vibrate and ignoring every other scan where number of taps modulo 2 != 0.

**Comment by JimmyPun610** [comment]
Hi @TedStryker ,
I updated the program to version 4.2.1.5 which added new property "AutoStartScanning", by default it is True.
In your case, you can set it the False.
Then, call the below function to start scanning.
```C#
GoogleVisionBarCodeScanner.Methods.SetIsScanning(true);
```
Reminder: Scanning will be stopped after every successful scan, you can manually enable by the above function
