### ISSUE TITLE
Changing VibationOnDetected is ignored in the app's lifecycle

### ISSUE THREAD

**Issue by TedStryker** [JimmyPun610/BarcodeScanner.XF#19]
I would like to let the phone vibrate if my business processes greenlight the scanned barcode.
If the barcode is not accepted, the phone should not vibrate but instead I display some red bar in the UI telling the user why the scanned barcode will not be accepted.

I would also very much appreciate if the length of vibration would be configurable.

And mind the typo in VibationOnDetected  plz ;-)

**Comment by JimmyPun610** [comment]
Hi @TedStryker 
In this case, I think you can do it in your project by DependencyService by below steps.
1. Set VibrationOnDetected to false
2. Check the barcode result in your business logic
3. If correct (greenlight), call vibration separately. If not, do not do anything.
#### Android implementation
```C#
Vibrator vib = (Vibrator)_context.GetSystemService(Context.VibratorService);
vib.Vibrate(lengthInMs);
```
#### iOS implementation
```C#
SystemSound.Vibrate.PlayAlertSound();
```

For the length of vibration, Android is available to customize but iOS seems to be impossible.
For the typo, I will fix it on the next release which will focus on another feature request raised by you.

**Comment by logi-26** [comment]
This is exactly how I am handling the vibration in my app.

If you are using Xamarin.Essentials plugin, that has a vibration funtion that excepts a vibration length:
var duration = TimeSpan.FromSeconds(1);
Vibration.Vibrate(duration);

But using this plugin on iOS the length is always 500 milliseconds.

**Comment by JimmyPun610** [comment]
Yes. When you look at the source code of it 
https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Vibration/Vibration.ios.cs

you will see they are using below code to vibrate. I think this is the restriction from iOS.
```C#
SystemSound.Vibrate.PlayAlertSound();
```
