### ISSUE TITLE
SetSupportBarcodeFormat allows to set just one format or all

### ISSUE THREAD

**Issue by janousek** [JimmyPun610/BarcodeScanner.XF#24]
Current implementation of SetSupportBarcodeFormat allows to set just one format or all. It is not possible to set multiple formats. 
Like: `Methods.SetSupportBarcodeFormat(BarcodeFormats.Pdf417 | BarcodeFormats.QRCode);`

This is because current implementation of `ConvertBarcodeFormats` uses switch:
https://github.com/JimmyPun610/BarcodeScanner.XF/blob/6de6a5535a5c541d7c5dbe5e15575c36ad2209bc/GoogleVisionBarCodeScanner.Droid/Methods.cs#L62
It should be implemented like this:
```
public static Android.Gms.Vision.Barcodes.BarcodeFormat ConvertBarcodeFormats(BarcodeFormats barcodeFormats)
        {
            Android.Gms.Vision.Barcodes.BarcodeFormat format = Android.Gms.Vision.Barcodes.BarcodeFormat.AllFormats;

            if((barcodeFormats & BarcodeFormats.CodaBar) == BarcodeFormats.CodaBar)
            {
                format |= Android.Gms.Vision.Barcodes.BarcodeFormat.Codabar;
            }
            if ((barcodeFormats & BarcodeFormats.Code128) == BarcodeFormats.Code128)
            {
                format |= Android.Gms.Vision.Barcodes.BarcodeFormat.Code128;
            }

            .....
            .....
            .....
            .....

            return format;
        }
```

**Comment by JimmyPun610** [comment]
> Current implementation of SetSupportBarcodeFormat allows to set just one format or all. It is not possible to set multiple formats.
> Like: `Methods.SetSupportBarcodeFormat(BarcodeFormats.Pdf417 | BarcodeFormats.QRCode);`
> 
> This is because current implementation of `ConvertBarcodeFormats` uses switch:
> 
> https://github.com/JimmyPun610/BarcodeScanner.XF/blob/6de6a5535a5c541d7c5dbe5e15575c36ad2209bc/GoogleVisionBarCodeScanner.Droid/Methods.cs#L62
> 
> 
> It should be implemented like this:
> ```
> public static Android.Gms.Vision.Barcodes.BarcodeFormat ConvertBarcodeFormats(BarcodeFormats barcodeFormats)
>         {
>             Android.Gms.Vision.Barcodes.BarcodeFormat format = Android.Gms.Vision.Barcodes.BarcodeFormat.AllFormats;
> 
>             if((barcodeFormats & BarcodeFormats.CodaBar) == BarcodeFormats.CodaBar)
>             {
>                 format |= Android.Gms.Vision.Barcodes.BarcodeFormat.Codabar;
>             }
>             if ((barcodeFormats & BarcodeFormats.Code128) == BarcodeFormats.Code128)
>             {
>                 format |= Android.Gms.Vision.Barcodes.BarcodeFormat.Code128;
>             }
> 
>             .....
>             .....
>             .....
>             .....
> 
>             return format;
>         }
> ```

Thanks @janousek 

I changed the code to use .HasFlag to check every formats.
Released the fix on version 4.2.2.2.

Thank you.
