### ISSUE TITLE
Remove Plugin.Permission

### ISSUE THREAD

**Issue by DottorPagliaccius** [JimmyPun610/BarcodeScanner.XF#25]
Hi, the new version of Xamarin.Essentials has a new permissions implementation, you should remove  Plugin.Permission (so I can remove mine).

Thanks,
Dottor Pagliaccius

**Comment by JimmyPun610** [comment]
Hi @DottorPagliaccius,

It's good to know that but I have some problems with updating Xamarin.Essential.
```
Failed to add reference. The package 'Xamarin.Essentials' tried to add a framework reference to 'System.Drawing.Common.dll' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
```

Maybe my network somehow blocked the installation or other issues. Hopefully I can finish it this week.

**Comment by JimmyPun610** [comment]
Updated to 4.2.2.3 which is applying Xamarin Essential 1.5.0 and removed Plugin.Permission and CurrentActivityPlugin

**Comment by DottorPagliaccius** [comment]
thank you ;)
