### ISSUE TITLE
Error when running scand view

### ISSUE THREAD

**Issue by lomsebas2** [JimmyPun610/BarcodeScanner.XF#26]
Hello, 
Implement the latest version and I get the following error when running on an Android Api 28 Android 9 

Xamarin Forms Version: 4.4.0.991864

I have Visual Studio 2019, download the repository and run the example and I get the same error

System.NotSupportedException
Message=Unable to activate instance of type Android.Util.SparseArray`1[E] from native handle 0x19 (key_handle 0xd3578f4).

![image](https://user-images.githubusercontent.com/62773412/77801188-5b4cc180-7046-11ea-94c4-f5a703703ba7.png)

![image](https://user-images.githubusercontent.com/62773412/77831189-ad035380-70fb-11ea-9ddf-4b690b981fc3.png)

![image](https://user-images.githubusercontent.com/62773412/77832190-1e460500-7102-11ea-8a36-ae8e5b8baf62.png)

Could you help me

**Comment by JimmyPun610** [comment]
Hi @lomsebas2 
What is your device, is that customized OS in China?

**Comment by omatrot** [comment]
I have the same problem on a Moto E4 Plus (XT1771) Android 7.1.1

**Comment by JimmyPun610** [comment]
HI @omatrot 
Is the device installed Google Play Services?

**Comment by omatrot** [comment]
@JimmyPun610 How can I check?

**Comment by JimmyPun610** [comment]
@omatrot 
https://play.google.com/store/apps/details?id=com.google.android.gms&hl=en

**Comment by omatrot** [comment]
It is installed on both devices

**Comment by JimmyPun610** [comment]
> It is installed on both devices. version is 20.9.14

Can you test in emulator?
I just try in a new emulator and it looks fine.

I cannot confirm the cause since I cannot reproduce your error but I think it could be error on Xamarin or Visual Studio.
My working configuration of emulator is Android 7.1
```
=== Visual Studio Community 2019 for Mac ===

Version 8.5 (build 3183)
Installation UUID: 24397c28-e256-4d1d-be50-67b614622bae
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.14.1.39 (d16-5 / 30e8706b4)

	Package version: 608000123

=== Mono Framework MDK ===

Runtime:
	Mono 6.8.0.123 (2019-10/1d0d939dc30) (64-bit)
	Package version: 608000123

=== Xamarin Designer ===

Version: 16.5.0.471
Hash: 35aa4889d
Branch: remotes/origin/d16-5
Build date: 2020-02-25 00:52:08 UTC

=== Roslyn (Language Service) ===

3.5.0-beta4-20125-04+1baa0b3063238ed752ad1f0368b1df6b6901373e

=== NuGet ===

Version: 5.4.0.6315

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.200/Sdks
SDK Versions:
	3.1.200
	3.1.102
	3.1.101
	3.0.100
	2.1.701
	2.1.700
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.2
	3.1.1
	3.0.0
	2.1.16
	2.1.15
	2.1.13
	2.1.12
	2.1.11
	2.0.5
	2.0.0

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.4 (16134)
Build 11E146

=== Xamarin.Mac ===

Version: 6.14.1.39 (Visual Studio Community)
Hash: 30e8706b4
Branch: d16-5
Build date: 2020-02-20 16:41:47-0500

=== Xamarin.iOS ===

Version: 13.14.1.39 (Visual Studio Community)
Hash: 30e8706b4
Branch: d16-5
Build date: 2020-02-20 16:41:48-0500

=== Xamarin.Android ===

Version: 10.2.0.100 (Visual Studio Community)
Commit: xamarin-android/d16-5/988c811
Android SDK: /Volumes/Untitled/AndroidSDK
	Supported Android versions:
		4.4 (API level 19)
		5.1 (API level 22)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.6
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: c0c5c78
Java.Interop: xamarin/java.interop/d16-5@fc18c54
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-5@9f4ed4b

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/chunhangpun/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.5.0.39
Hash: 6fb4c79
Branch: remotes/origin/d16-5
Build date: 2020-02-20 23:25:56 UTC

=== Android Device Manager ===

Version: 16.5.0.71
Hash: 49194e8
Branch: remotes/origin/d16-5
Build date: 2020-02-20 23:26:18 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 805003183
Git revision: 60e06e010baa677204535600661dda3fb4677c2f
Build date: 2020-03-20 06:18:03-04
Build branch: release-8.5
Xamarin extensions: 60e06e010baa677204535600661dda3fb4677c2f

=== Operating System ===

Mac OS X 10.15.3
Darwin 19.3.0 Darwin Kernel Version 19.3.0
    Thu Jan  9 20:58:23 PST 2020
    root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
```

**Comment by omatrot** [comment]
Ok this is weird, but after a rebuild all, the problem vanished. Sorry about that.

**Comment by lomsebas2** [comment]
Hello, I still have the problem in Visual Studio 2019 Preview version 16.6.0 for Windows

Compile the project in Visual Studio 2017 version: 15.9.21 for windows and it works only with Multi-Dex which I have to verify camera permissions separately

**Comment by JimmyPun610** [comment]
> Hello, I still have the problem in Visual Studio 2019 Preview version 16.6.0 for Windows
> 
> Compile the project in Visual Studio 2017 version: 15.9.21 for windows and it works only with Multi-Dex which I have to verify camera permissions separately

Hi @lomsebas2 
You can also try 
1. Rebuild all.
2. Try not to use preview version of Visual Studio.

For Multi-Dex issue, it is restricted by Android OS and I cannot do anything.
FYI
https://developer.android.com/studio/build/multidex
