### ISSUE TITLE
Scanner is not working on some devices

### ISSUE THREAD

**Issue by GiorgosBetsos** [JimmyPun610/BarcodeScanner.XF#27]
I made an application using the library. The scanner works fine on a couple of devices, but doesn't work at all one some other. For example it doesn't work on Cat S31 or on Nokia 7.1 with Android Oreo v. 8.1.

**Comment by JimmyPun610** [comment]
Any error from the device while scanning the barcode?
You may use the sample app to try it.

I would need more information to work on it

**Comment by GiorgosBetsos** [comment]
This is the source code I'm using:

**.xaml** file:

```
<ContentPage.Content>
     <StackLayout>
         <!--Fill the screen with CameraView-->
         <gv:CameraView HorizontalOptions="FillAndExpand" 
                        VerticalOptions="FillAndExpand"
                        OnDetected="CameraView_OnDetected"                    
                        HeightRequest="380"                           
                        DefaultTorchOn="False"                            
                        VibrationOnDetected="False" 
                        AutoStartScanning="True"/>                      
     </StackLayout>        
</ContentPage.Content>

```
**.cs** file:

 ```
 public BarcodeScanXFPage()
 {
       InitializeComponent();
            GoogleVisionBarCodeScanner.Methods.SetSupportBarcodeFormat(GoogleVisionBarCodeScanner.BarcodeFormats.Itf);
  }

  protected override void OnAppearing()
  {
       base.OnAppearing();
       // once the barcode scan page appears start immediately scanning ...       GoogleVisionBarCodeScanner.Methods.SetSupportBarcodeFormat(GoogleVisionBarCodeScanner.BarcodeFormats.Itf);

   GoogleVisionBarCodeScanner.Methods.SetIsScanning(true);            
  }

private void CameraView_OnDetected(object sender, GoogleVisionBarCodeScanner.OnDetectedEventArg e)
{
        List<GoogleVisionBarCodeScanner.BarcodeResult> obj = e.BarcodeResults;

        string CardNr;
                       
        Device.BeginInvokeOnMainThread(async () =>
         {
                if (obj.Count > 0)
                {
                    CardNr = obj[0].DisplayValue;
                    
                    await DisplayAlert("Scan result", $"Card Nr {CardNr}", "OK");

```
This works perfectly well in a Xiaomi RedmiNote 6 Pro with Android 9.0 but fails in Cat S31 (Android Oreo v. 8.1) or on Nokia 7.1 (Android v. 10).

**Comment by JimmyPun610** [comment]
You may try to reference the library project directly and set a breakpoint in the detected barcode event in Android Project(library one) to see whether the problem is due to barcode cannot detected in those devices or there is any bug in handling the detection. 

I got a Nokia 5.1 with Android 10, could you please provide a sample barcode for me (your testing barcode would be great if possible) so that I could try to reproduce it

**Comment by GiorgosBetsos** [comment]
This is a card that the scanner fails to scan. The same card is successfully scanned with a Samsung Galaxy or Xiaomi Redmi Note6 Pro device, but not with a Cat S31 or Nokia 7.1 device.

I can't see how I could use the emulator to debug the barcode scanner (and so to be able to place a breakpoint anywhere in code).

![Card](https://user-images.githubusercontent.com/18726683/79420028-b0825000-7fc0-11ea-88e9-179ee6913b83.jpeg)

**Comment by GiorgosBetsos** [comment]
I just got it to work on the Cat device! The only thing I did was to wipe out all bin/obj folders and rebuild the solution. The scanner now works ok.

**Comment by JimmyPun610** [comment]
> I just got it to work on the Cat device! The only thing I did was to wipe out all bin/obj folders from both Forms,Android folders and rebuild the solution. The scanner now works ok.

This is good. I also tested in my Nokia 6.1 and it runs normally.
BTW, You can use your device to debug
