### ISSUE TITLE
Adding this NuGet will make iOS project fail to build

### ISSUE THREAD

**Issue by VahidShir** [JimmyPun610/BarcodeScanner.XF#28]
Thanks for your great and helpful library.

### Description
After upgrading to latest Visual Studio version (16.5.4) the iOS project fails to build in Release/Ad-Hoc mode with this message:
`error MT2002: Failed to resolve "Xamarin.Forms.Platform.iOS.IndicatorViewRenderer" reference from "Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null`

After some investigations I narrowed down the problem to your package. I found out that after adding it, some types are no longer resolvable (such as _IndicatorViewRenderer_). The iOS project works fine in debug mode but not in release mode. If I set Linker mode to "Don't Link" the project would build successfully.
Android has not any problem.
Here's a similar discussion:
[https://forums.xamarin.com/discussion/180561/xamarin-forms-platform-ios-indicatorviewrenderer-fails-to-resolve](https://forums.xamarin.com/discussion/180561/xamarin-forms-platform-ios-indicatorviewrenderer-fails-to-resolve)

### Steps to Reproduce
1. Create a blank Xamarin.Forms project
2. Update default NuGet packages to latest versions (Xamarin.Forms --> 4.5.0.617, Xamarin.Essentials --> 1.5.2)
3. Observe that the type Xamarin.Forms.Platform.iOS.IndicatorViewRenderer is accessible.
4. Add BarcodeScanner.XF package to projects
5. Rebuild solution.
6. The type Xamarin.Forms.Platform.iOS.IndicatorViewRenderer is no longer accessible.

### Basic Information
Visual Studio: 16.5.4
Xamarin.Forms: 4.5.0.617
BarcodeScanner.XF: 4.2.2.3

**Comment by JimmyPun610** [comment]
Noted. Probably need to update package version to Xamarin Form 4.5, will fix it asap

**Comment by JimmyPun610** [comment]
Update to 4.5.0.1 which is supporting Xamarin Form 4.5+.

**Comment by GaboMendez** [comment]
Hey i have this issue, somebody know how to resolve it?

**Comment by JimmyPun610** [comment]
> Hey i have this issue, somebody know how to resolve it?

Please provide your
1. Visual Studio version
2. Xamarin Forms version
3. BarcodeScanning.XF package version.

This issue mainly caused by the version difference between Xamarin Form and BarcodeScanning.XF

**Comment by GaboMendez** [comment]
Thanks bro, i found a solution! 

Regards!!
