### ISSUE TITLE
Adding this nuget makes Xamarin.iOS project fail to build

### ISSUE THREAD

**Issue by terencelister** [JimmyPun610/BarcodeScanner.XF#29]
**Description**
After upgrading to latest nuget (version 4.5.0.1) the Xamarin.iOS project fails to build in Debug and Release mode with this message:

MTOUCH : error MT2101: Can't resolve the reference 'System.Collections.Generic.IDictionary`2<System.Int32,System.Collections.Generic.List`1<Xamarin.Forms.ITabStopElement>> Xamarin.Forms.TabIndexExtensions::GetTabIndexesOnParentPage(Xamarin.Forms.ITabStopElement,System.Int32&,System.Boolean)', referenced from the method 'UIKit.UIView Xamarin.Forms.Platform.iOS.VisualElementRenderer`1::FocusSearch(System.Boolean)' in 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.

I narrowed it down to this package.  If I set Linker mode to "Don't Link" it builds successfully. This isn't a problem in Android. The Xamarin.Firebase.iOS.MLKit version 0.13.0.2 drags in the Xamarin.Forms.Core requirement and the other packages in my application require later versions of Xamarin.Forms.Core causing the issue.

**Steps to Reproduce**

1. git clone BarcodeScanner.XF
2. Modify build to linker behavior selection to "Link All"
3. Build SamleApp.iOS
4. The MT2101 error from above occurs.

**Basic Information**
Visual Studio for Mac: 8.5.4
Xamarin.Forms: 4.5.0.617
BarcodeScanner.XF: 4.5.0.1

**Comment by JimmyPun610** [comment]
BarcodeScanner.XF 4.5.0.2 is released for Xamarin Form 4.5.0.617
Tested with Link Framework SDKs only and Link All in iOS. Please let me know if the problem still exist

**Comment by VahidShir** [comment]
I had exactly the same issue. I can confirm that after upgrading to latest version (i.e 4.5.0.3) my iOS project now builds successfully in Release/Ad-Hoc modes.
Here's my configurations:
Visual Studio: 16.5.4
Xamarin.Forms: 4.5.0.617
BarcodeScanner.XF: 4.5.0.3

Thanks @JimmyPun610

**Comment by JimmyPun610** [comment]
Please use 4.5.0.3 for XF 4.5.0.617+
