### ISSUE TITLE
Unable to resolve dependencies. 'Xamarin.Forms 4.5.0.657' is not compatible with 'BarcodeScanner.XF 4.5.0.2 constraint: Xamarin.Forms (= 4.5.0.617)'.

### ISSUE THREAD

**Issue by DottorPagliaccius** [JimmyPun610/BarcodeScanner.XF#30]
Hi!

When updating XF: 

"Unable to resolve dependencies. 'Xamarin.Forms 4.5.0.657' is not compatible with 'BarcodeScanner.XF 4.5.0.2 constraint: Xamarin.Forms (= 4.5.0.617)'."

Shouldn't be ">=" ?

**Comment by fgbustoa** [comment]
Up

**Comment by JimmyPun610** [comment]
Sorry about that. Please update to 4.5.0.3 for XF4.5.0.617+

**Comment by DottorPagliaccius** [comment]
oh, I've done so many mistakes with NuGet ;) Thank you
