### ISSUE TITLE
Building iOS project fails 

### ISSUE THREAD

**Issue by remco-rebelit** [JimmyPun610/BarcodeScanner.XF#31]
Building iOS project with linking SDK only fails when using Forms 4.6.0.726 

error MT2002: Failed to resolve "Xamarin.Forms.Platform.iOS.RadioButtonRenderer" reference from "Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null

Seems related to the issue with Forms 4.5

**Comment by JimmyPun610** [comment]
Noted. 
Will update the project with XF4.6.0.726 later

**Comment by JimmyPun610** [comment]
The package is updated and build successfully according to AppCenter.
But I have not test it yet, please do me a favour on testing it.

Please use 4.6.0.1 with XF 4.6+ and read about readme.md as there is additional settings in your AppDelegate.cs

**Comment by remco-rebelit** [comment]
Thanks! It works

**Comment by GaboMendez** [comment]
"Please use 4.6.0.1" what packages do i use in this version? to resolve this issue...

**Comment by GaboMendez** [comment]
To resolve this issue https://github.com/JimmyPun610/BarcodeScanner.XF/blob/master/ReleaseNotes/4.6.0.2.md
