### ISSUE TITLE
System.NotSupportedException

### ISSUE THREAD

**Issue by larsk2009** [JimmyPun610/BarcodeScanner.XF#34]
Hi there.

I am having some trouble running the example project. When I open any camera view, I get the error below:

`System.NotSupportedException: 'Unable to activate instance of type Android.Util.SparseArray`

I am on VS2019 community and Android 10.

I have a feeling I know what the solution is. I have found [this issue](https://developercommunity.visualstudio.com/content/problem/1050379/unable-to-activate-instance-of-type-androidutilspa.html) from 3 days ago on the VS developer community. It talks about a camera view which I would think is similar to how the cameraview in this project works. Someone made a comment there saying it was solved when moving to VS2019 preview, specifically VS16.7 preview 1. I will try this and update the issue accordingly.

Just wanted to make this issue so you and others are aware of this, I don't think it is something that can be solved by you but is something with VS. Again, I'll update if using the preview version solves my problem.

**Comment by larsk2009** [comment]
I can confirm using Visual Studio 16.7 preview 1 fixes this. So probably nothing you can do about it, but still good to know if someone else has this issue.

**Comment by JimmyPun610** [comment]
I tried my project.
Seems it related to the target framework of the android project.
I made below changes and the sample project seems working.
1. Change Target Framework from Android 9 to Android 10
2. Install Nuget Package Xamarin.AndroidX.MediaRouter

I would switch my library to target Android 10 later to see it is solved or not but you may able to try above workaround for this moment.

**Comment by larsk2009** [comment]
I haven't had time to check the workaround you suggested, but it seems that [VS 16.6.1](https://docs.microsoft.com/nl-nl/visualstudio/releases/2019/release-notes#16.6.1) which was released on 2020-06-01 (yesterday) seems to fix the issue as well, so I guess this can be closed?

**Comment by JimmyPun610** [comment]
Yeah I just tested and it did not work.
Or you can wait 1 to 2 days more for me to update the library. 
Basically is about the Android target framework.

**Comment by larsk2009** [comment]
Yeah you are right with the android framework. I did your workaround and works very well, thank you!

**Comment by JimmyPun610** [comment]
You may update to 4.6.1 which is updated the package reference for target framework 9 and 10.
