### ISSUE TITLE
Delay scanning best practice

### ISSUE THREAD

**Issue by sunnyatticsoftware** [JimmyPun610/BarcodeScanner.XF#35]
Great library by the way!

I was wondering what's the recommended approach when scanning continuously with `Methods.SetIsScanning(true);` to allow certain delay between scans.

Would you sleep the thread or is there a better alternative with Xamarin forms?

**Comment by JimmyPun610** [comment]
Hi @sunnyatticsoftware 

Thank you.
For your question, it depends on what you want the program to behave.
I can provide some hints for you.
1. Use Device.StartTimer (Xamarin provided function)
[https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.device.starttimer?view=xamarin-forms](url)
2. Use Rx (System.Reactive.Linq)
```C#
Observable.Timer(TimeSpan.FromSeconds(5)).Subscribe(x => {
			//Do your work
		});
```

**Comment by sunnyatticsoftware** [comment]
Thanks for your quick reply. I'll try those things.
Basically my scenario is.. I want to scan several barcodes one after another, and do something for each scan result.
But I wanted to add a delay between scans, otherwise it will read the same barcode several times.

**Comment by JimmyPun610** [comment]
For this, you can refer to the sample app "Continuous Scanning", the basic idea is when barcode detected, do the work in the event and call SetIsScanning method at the end of the event
