### ISSUE TITLE
Error- System.NotSupportedException   Message=Unable to activate instance of type Android.Util.SparseArray`1[E] from native handle 0x11 (key_handle 0xd807fbf).

### ISSUE THREAD

**Issue by Atharva-Peshkar** [JimmyPun610/BarcodeScanner.XF#37]
I replicated your SampleApp code and when I press the 'start scanning' button for page 3 i.e. continous scanning and run it in the debugging mode on my device the app breaks and I get the following error in VS Code 2019

System.NotSupportedException
  Message=Unable to activate instance of type Android.Util.SparseArray`1[E] from native handle 0x11 (key_handle 0xd807fbf).

Can you please help me solve this issue.

**Comment by JimmyPun610** [comment]
Hi @Atharva-Peshkar 
Just wonder which version are you using?
you can refer to #34 to see whether it can be solved or not

**Comment by Atharva-Peshkar** [comment]
> Hi @Atharva-Peshkar
> Just wonder which version are you using?
> you can refer to #34 to see whether it can be solved or not

I am using Xamarin Forms 4.6.0.847 with BarcodeScanner.XF 4.6.1 and Android 9 (Redmi Note 7 Pro)

**Comment by JimmyPun610** [comment]
Hi @Atharva-Peshkar 

I tested in my Nokia 6.1 with Android 10 and it is still working and I will try to find a RedMI (in case I have) to test it.

But for my guess, it should be the linking issue between Android and Xamarin and there is not many things I can do.
I just did some google job and there is a similar issue in [https://github.com/xamarin/xamarin-android/issues/4795](Xamarin Github)

What I can suggest is
1. Close the solution, remove all bin/obj folder in each project
2. Update your VS to latest version
3. Set target framework in Android 10 (R) (not Q) / Android 9
4. Rebuild the solution and test.

**Comment by Atharva-Peshkar** [comment]
> Hi @Atharva-Peshkar
> 
> I tested in my Nokia 6.1 with Android 10 and it is still working and I will try to find a RedMI (in case I have) to test it.
> 
> But for my guess, it should be the linking issue between Android and Xamarin and there is not many things I can do.
> I just did some google job and there is a similar issue in [https://github.com/[xamarin/xamarin-android/issues/4795](https://github.com/xamarin/xamarin-android/issues/4795)](Xamarin Github)
> 
> What I can suggest is
> 
> 1. Close the solution, remove all bin/obj folder in each project
> 2. Update your VS to latest version
> 3. Set target framework in Android 10 (R) (not Q) / Android 9
> 4. Rebuild the solution and test.

Hi @JimmyPun610 

Thank you so much! My issue is solved.

**Comment by JimmyPun610** [comment]
> > Hi @Atharva-Peshkar
> > I tested in my Nokia 6.1 with Android 10 and it is still working and I will try to find a RedMI (in case I have) to test it.
> > But for my guess, it should be the linking issue between Android and Xamarin and there is not many things I can do.
> > I just did some google job and there is a similar issue in [https://github.com/[xamarin/xamarin-android/issues/4795](https://github.com/xamarin/xamarin-android/issues/4795)](Xamarin Github)
> > What I can suggest is
> > 
> > 1. Close the solution, remove all bin/obj folder in each project
> > 2. Update your VS to latest version
> > 3. Set target framework in Android 10 (R) (not Q) / Android 9
> > 4. Rebuild the solution and test.
> 
> Hi @JimmyPun610
> 
> Thank you so much! My issue is solved.

@Atharva-Peshkar Good to know that. Would you mind to share how to solve it?

**Comment by tonyyu1** [comment]
> > > Hi @Atharva-Peshkar
> > > I tested in my Nokia 6.1 with Android 10 and it is still working and I will try to find a RedMI (in case I have) to test it.
> > > But for my guess, it should be the linking issue between Android and Xamarin and there is not many things I can do.
> > > I just did some google job and there is a similar issue in [https://github.com/[xamarin/xamarin-android/issues/4795](https://github.com/xamarin/xamarin-android/issues/4795)](Xamarin Github)
> > > What I can suggest is
> > > 
> > > 1. Close the solution, remove all bin/obj folder in each project
> > > 2. Update your VS to latest version
> > > 3. Set target framework in Android 10 (R) (not Q) / Android 9
> > > 4. Rebuild the solution and test.
> > 
> > 
> > Hi @JimmyPun610
> > Thank you so much! My issue is solved.
> 
> @Atharva-Peshkar Good to know that. Would you mind to share how to solve it?

I have the exact same issue and my workaround is to use Visual Studio 2017 with Xamarin.Android 10.2.

**Comment by Atharva-Peshkar** [comment]
> > > Hi @Atharva-Peshkar
> > > I tested in my Nokia 6.1 with Android 10 and it is still working and I will try to find a RedMI (in case I have) to test it.
> > > But for my guess, it should be the linking issue between Android and Xamarin and there is not many things I can do.
> > > I just did some google job and there is a similar issue in [https://github.com/[xamarin/xamarin-android/issues/4795](https://github.com/xamarin/xamarin-android/issues/4795)](Xamarin Github)
> > > What I can suggest is
> > > 
> > > 1. Close the solution, remove all bin/obj folder in each project
> > > 2. Update your VS to latest version
> > > 3. Set target framework in Android 10 (R) (not Q) / Android 9
> > > 4. Rebuild the solution and test.
> > 
> > 
> > Hi @JimmyPun610
> > Thank you so much! My issue is solved.
> 
> @Atharva-Peshkar Good to know that. Would you mind to share how to solve it?

Sure!

**Comment by Atharva-Peshkar** [comment]
I am using VS Code Community 2019 with Android 9 on Redmi 7 Pro. In my case I updated all the packages (dependencies) to their latest version and rebuilt the project. That worked for me!
