### ISSUE TITLE
Dark camera preview

### ISSUE THREAD

**Issue by brxtr** [JimmyPun610/BarcodeScanner.XF#38]
Testing the sample app with my Moto G (4) with Android 6.0.1 the camera preview is noticeably darker than the stock camera app. I believe this is because the FPS is too high for the dynamic exposure to work. There is probably a more sophisticated solution, but I found that setting the FPS with `CameraSource.Builder.SetRequestedFps()` fixed the issue. The maximum value to 1 dp that worked for me was `17.5f`. Perhaps a configuration parameter could be added for FPS to allow this to be fixed while also allowing a higher FPS if that is preferred?

**Comment by JimmyPun610** [comment]
Hi @brxtr 

You may try 4.7.0.1 which allow you to set the RequestedFPS in xaml.
I didnt test it yet though.

It would be nice if you could let me know the result

**Comment by brxtr** [comment]
It looks like it's working. Thanks for the quick response!
