### ISSUE TITLE
Android v10(q10)

### ISSUE THREAD

**Issue by ghotekarduryo** [JimmyPun610/BarcodeScanner.XF#40]
07-15 12:36:16.228 I/DynamiteModule(24171): Considering local module com.google.android.gms.vision.barcode:0 and remote module com.google.android.gms.vision.barcode:0
07-15 12:36:16.229 E/Vision  (24171): Error loading module com.google.android.gms.vision.barcode optional module true: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
07-15 12:36:16.229 W/DynamiteModule(24171): Local module descriptor class for com.google.android.gms.vision.dynamite.barcode not found.
07-15 12:36:16.238 D/ViewRootImpl@71a4cd2[MainActivity](24171): ViewPostIme pointer 1
07-15 12:36:16.246 I/DynamiteModule(24171): Considering local module com.google.android.gms.vision.dynamite.barcode:0 and remote module com.google.android.gms.vision.dynamite.barcode:0
07-15 12:36:16.247 D/BarcodeNativeHandle(24171): Cannot load feature, fall back to load dynamite module.
07-15 12:36:16.261 W/DynamiteModule(24171): Local module descriptor class for com.google.android.gms.vision.barcode not found.
07-15 12:36:16.261 I/DynamiteModule(24171): Considering local module com.google.android.gms.vision.barcode:0 and remote module com.google.android.gms.vision.barcode:0
07-15 12:36:16.262 E/Vision  (24171): Error loading module com.google.android.gms.vision.barcode optional module true: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.

**Comment by JimmyPun610** [comment]
Please try to enable internet for the device in the first launch.

**Comment by ghotekarduryo** [comment]
i have disabled wifi and then started app with mobile data even though its not scanning. other mobile devices are getting suportted nut those device are not getting supported for Android version 10 or Version 9. another problem is that few deivces with same os are supporting are few devices are not supporting. Example Samsung M31 is not supporting but redmi Note 8 Pro is supporting which has Android version 9. Please do needful we are stuck since last couple of day and shared issued with you today morning.

**Comment by ghotekarduryo** [comment]
in addition to this we have found another issue on those devices scanner is supporting only if WIFi is Enable. on mobile data none of the mobile device support this scanners. We are unable to find out reason and issue to rectify it.

**Comment by JimmyPun610** [comment]
https://stackoverflow.com/questions/58477758/android-studio-ml-kit-cannot-load-ocr-module

could you verify the google play services version of those supporting devices and not supporting devices?

there is nothing I can do in coding level

**Comment by themaxsmith** [comment]
This goes in line with why I think we should switch to Xamarin.Firebase.ML.Vision. I think it is static & does not need to download the models from Google Play Services.

**Comment by JimmyPun610** [comment]
closed due to no update
