### ISSUE TITLE
Code 39 Not Working

### ISSUE THREAD

**Issue by themaxsmith** [JimmyPun610/BarcodeScanner.XF#41]
Everything works great other than barcode type code 39 on Andriod. Also very excited about the future of this project. Hope this can be resolved.

**Comment by JimmyPun610** [comment]
looks I forgot to add code39 checking on Android source.
I fixed in 4.7.0.2, could you please help to try if it is work? 
I do not have Android device right now.

Thank you

**Comment by themaxsmith** [comment]
Works great! Thank you I appreciate the fast response & release.
