### ISSUE TITLE
CameraView_OnDetected not firing

### ISSUE THREAD

**Issue by dariobalas** [JimmyPun610/BarcodeScanner.XF#43]
Hi Jimmy,

I downloaded your sample project and for some reason CameraView_OnDetected is not firing. I am trying to scan QR code using Nokia 5 with Android 9. Also, if i click scan from image button, it freezes. It did ask me for permissions to access camera and storage. Any idea what could be the problem?

Thanks!

Dario

**Comment by JimmyPun610** [comment]
So the freezing problem is coming before or after you selected the image?
I tried in my simulator and found out that the problem is between line 58-61 in MainPage.xaml.cs.
It is simply an error of permission checking implementation and not related to the library at all and it is not going to happen again after you restart the app.

**Comment by JimmyPun610** [comment]
You may change the sample source from
```C#
     while(storageStatus != PermissionStatus.Granted)
            {
               await Permissions.RequestAsync<Permissions.StorageRead>();
            }
```

to


```C#
     while(storageStatus != PermissionStatus.Granted)
            {
                storageStatus = await Permissions.RequestAsync<Permissions.StorageRead>();
            }

```

This should tackle your issue

**Comment by dariobalas** [comment]
Thanks. Will give it a shot and let you know how it goes. It doesnt even open the window to select the image. 

How about that event CameraView_OnDetected not firing? It is very clear qr code i tried to scan but it is not firing. Also tried with barcode. Strange. Will try with another phone.

**Comment by dariobalas** [comment]
Thanks. It worked for pictures. Only thing i also had to change is to add a file content check because if i click cancel button when uploading from image, app would crash with null exception so just changed it to this:

`if(file != null)
                {
                    Stream stream = file.GetStream();
                    byte[] bytes = new byte[stream.Length];
                    stream.Read(bytes, 0, bytes.Length);
                    stream.Seek(0, SeekOrigin.Begin);
                    List<GoogleVisionBarCodeScanner.BarcodeResult> obj = await GoogleVisionBarCodeScanner.Methods.ScanFromImage(bytes);
                    if (obj.Count > 0)
                    {
                        string result = string.Empty;
                        for (int i = 0; i < obj.Count; i++)
                        {
                            result += $"Type : {obj[i].BarcodeType}, Value : {obj[i].DisplayValue}{Environment.NewLine}";
                        }
                        Device.BeginInvokeOnMainThread(async () =>
                        {
                            await DisplayAlert("Result", result, "OK");
                        });
                    }
                    else
                    {
                        Device.BeginInvokeOnMainThread(async () =>
                        {
                            await DisplayAlert("Result", "No barcode found!", "OK");
                        });
                    }
                }`

Also CameraView_OnDetected is firing on a bit older Samsung Galaxy S5 with Android 6 installed but not on Nokia 5 with Android 9. Tried changing target framework in the back end but it did not help.

**Comment by JimmyPun610** [comment]
For the CameraView_OnDetected is not fired issue, are you using Scan from Camera or from Image?

**Comment by dariobalas** [comment]
Scanning from the camera. But as i said, on Samsung it fires the event when scanning with camera and on Nokia doesnt.

**Comment by JimmyPun610** [comment]
@dariobalas 
That is strange. Does it happen to all QRcode?
and any error message?

**Comment by dariobalas** [comment]
Hi Jimmy,

You are right. Really didnt see this one coming... Didnt even think it is possible that a relatively new phone (in comparing with old Samsung) is NOT capable to scan QR codes... Sorry for wasting your time. Thank you for your help and a great app!

Regards,
Dario
