### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by MisterAcoustic** [JimmyPun610/BarcodeScanner.XF#44]
Hello, could you please add a license file to clarify how this code can be used?

I am hopeful that you will choose an Apache or MIT style license :).

Thanks!

**Comment by JimmyPun610** [comment]
@MisterAcoustic 
Sure, added MIT license

**Comment by MisterAcoustic** [comment]
Thank you very much! I love what I've seen so far, and hope to offer up some feature enhancements for your review.
