### ISSUE TITLE
Changes to GoogleVisionBarCodeScanner not picked up because SampleApp references NuGet instead of project

### ISSUE THREAD

**Issue by MisterAcoustic** [JimmyPun610/BarcodeScanner.XF#45]
Hello - I'd very much like to add some features for your consideration. However, the SampleApp references the NuGet package, rather than the GoogleVisionBarCodeScanner project.

I don't have much experience in this area. How can I either create a NuGet package from the code in my version of the GoogleVisionBarCodeScanner project, or have the SampleApp refer to the project in the solution? I tried to remove the package reference, but ended up missing more things than I expected.

Any help is appreciated, thanks!

**Comment by JimmyPun610** [comment]
Removing package reference and add the project reference in sample app should work.

Or you can create the package first, add local nuget path. But it will not able to debug.

**Comment by MisterAcoustic** [comment]
Thanks - I have resolved my issue. I think part of it was a Visual Studio hiccup. Off to the races! :)

So far, I have a quick shot at returning the CornerPoints data in BarcodeResult, which should allow for both custom on-screen feedback, and a quick and dirty hack for 'aimed' scanning (by checking if the points fall within a known rectangle/region.

I appreciate the help!

**Comment by JimmyPun610** [comment]
@MisterAcoustic 
It's good to hear that. Could you share your code or create a pull request for this function?

**Comment by MisterAcoustic** [comment]
@JimmyPun610 
Hello - I believe I will be able to provide the code that we end up with, but I'm not sure it will be in the form of a pull request. I can show you what we've done and let you decide if it's worthwhile to add that way. The mapping of the points from the camera to the screen in Xamarin Forms was a little more challenging than expected. Android is working completely now, but iOS needs a different type of transformation, and I'm still looking into that. The changes to the library are not that extensive - we are doing the mapping in our application, so I'll have to get that into the sample app somewhere for you to see that part. I hope to nail down iOS next week. After that, I will get in touch and let you see what we've done.

**Comment by JimmyPun610** [comment]
> @JimmyPun610
> Hello - I believe I will be able to provide the code that we end up with, but I'm not sure it will be in the form of a pull request. I can show you what we've done and let you decide if it's worthwhile to add that way. The mapping of the points from the camera to the screen in Xamarin Forms was a little more challenging than expected. Android is working completely now, but iOS needs a different type of transformation, and I'm still looking into that. The changes to the library are not that extensive - we are doing the mapping in our application, so I'll have to get that into the sample app somewhere for you to see that part. I hope to nail down iOS next week. After that, I will get in touch and let you see what we've done.

Sure. Take your time
