### ISSUE TITLE
customize barcode scanner view and tLaserColor

### ISSUE THREAD

**Issue by ghotekarduryo** [JimmyPun610/BarcodeScanner.XF#46]
How to set width and Height of  CameraView
![ac](https://user-images.githubusercontent.com/26179663/96835142-ce91a700-1460-11eb-9edb-6f002bd87fa5.png)

**Comment by JimmyPun610** [comment]
> How to set width and Height of CameraView
> ![ac](https://user-images.githubusercontent.com/26179663/96835142-ce91a700-1460-11eb-9edb-6f002bd87fa5.png)

Hi @ghotekarduryo 

Seems it is not able to set by the WidthRequest and HeightRequest directly,
I suggest you put the camera view inside a grid view and then set the size of the grid view as a workaround.

**Comment by ghotekarduryo** [comment]
how to set lesar line

**Comment by JimmyPun610** [comment]
> how to set lesar line

the library only provides functions to scan the qrcode and the camera view of it.
You may add all your view into a relativelayout and arrange their position.

**Comment by ghotekarduryo** [comment]
customize barcode scanner view and tLaserColor
 as like below images same with Transparent images

**Comment by JimmyPun610** [comment]
> customize barcode scanner view and tLaserColor
> as like below images same with Transparent images as Like Paytm QR Code Scanner Camera View
> ![ac](https://user-images.githubusercontent.com/26179663/96852615-fa1f8c00-1476-11eb-9e66-4724cc5a92ec.png)

This is out of the scope of this library.
This library provides a camera view with the function of scanning barcode.
For the overlap, laser line and others UI component, you can customize it in your project.
