### ISSUE TITLE
Random OnDetected invoked when not actively scanning QR codes

### ISSUE THREAD

**Issue by LeoJHarris** [JimmyPun610/BarcodeScanner.XF#47]
Hi there! Thanks for what appears to be a great QR code scanner 👍  one issue I noticed however is I have a tabbed page with 2 child pages, one happens to be a page with a QR code scanner view in it to scan items and another page has scanned barcodes. I noticed randomly that on the scanned barcodes page the app/device randomly vibrated and scanned as though it was scanning a barcode but I didn't even have a barcode being scanned in front of the device. I put break point in on the OnDetected event method to see the result and looks like following:

![Capture](https://user-images.githubusercontent.com/5468757/98304025-0df4f180-2024-11eb-85eb-96ff84262b34.PNG)

It seems rather odd it would randomly trigger the QR code OnDetected event. Would there be a reason for this since I don't even have a QR code in front of the camera?

**Comment by JimmyPun610** [comment]
Hi @LeoJHarris 

Thank you.
After investigation on the provided screenshot, the barcode scanner may detect a barcode you do not expect as the sensor is quite sensitive and it serves many kinds of barcodes, so I suggest you try to narrow down the supporting barcode types.
If your application is designed only for a certain barcode format such as QRCode you should call GoogleVisionBarCodeScanner.Methods.SetSupportBarcodeFormat.

```C#
//Default All
//Set detect QRCode only
GoogleVisionBarCodeScanner.Methods.SetSupportBarcodeFormat(BarcodeFormats.QRCode);
//Set detect QRCode + Code39
GoogleVisionBarCodeScanner.Methods.SetSupportBarcodeFormat(BarcodeFormats.QRCode | BarcodeFormats.Code39);
```
2.

**Comment by JimmyPun610** [comment]
closed due to no update
