### ISSUE TITLE
iOS: Unhandled Managed Exception thrown on app start when camera permission denied

### ISSUE THREAD

**Issue by pablo-gasparinid** [JimmyPun610/BarcodeScanner.XF#48]
After denying permissions on iOS, every time the app is started, it crashes with the following exception.

```
Unhandled managed exception: Could not initialize an instance of the type 'AVFoundation.AVCaptureDeviceInput': the native 'initWithDevice:error:' method returned nil.
It is possible to ignore this condition by setting ObjCRuntime.Class.ThrowOnInitFailure to false. (System.Exception)
  at Foundation.NSObject.InitializeHandle (System.IntPtr handle, System.String initSelector) [0x000a8] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/Foundation/NSObject2.cs:504 
  at AVFoundation.AVCaptureDeviceInput..ctor (AVFoundation.AVCaptureDevice device, Foundation.NSError& error) [0x00027] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/AVCaptureDeviceInput.g.cs:80 
  at GoogleVisionBarCodeScanner.UICameraPreview.Initialize (System.Boolean defaultTorchOn, System.Boolean vibrationOnDetected, System.Boolean startScanningOnCreate) [0x0009d] in <d513dc25a3de4543b7e74dac86eab609>:0 
  at GoogleVisionBarCodeScanner.UICameraPreview..ctor (System.Boolean d<…>
```

iOS version: 13.7
Xamarin.Forms version: 4.8.0.1451

**Comment by JimmyPun610** [comment]
Is your app showing the camera view at start?

Generally, you should not display the camera view if the permission is denied.

**Comment by pablo-gasparinid** [comment]
No, the camera is only used for QR Code scanning and it's on a modal page that is navigated to manually.

**Comment by JimmyPun610** [comment]
> No, the camera is only used for QR Code scanning and it's on a modal page that is navigated to manually.
> The app cannot even get to that modal page after the permissions have been denied.

I suggest you check the camera permission before get into the modal page.

**Comment by pablo-gasparinid** [comment]
> > No, the camera is only used for QR Code scanning and it's on a modal page that is navigated to manually.
> > The app cannot even get to that modal page after the permissions have been denied.
> 
> I suggest you check the camera permission before get into the modal page.

I think I didn't explain myself properly. The scenario is the following:

1. Open the app for the first time. There's no camera needed at this point
2. There's a menu button (in my app) to go to the Scan QQ Code page, tap on that button
3. The app navigates to the page with the QR Code scanner
4. The user taps on a button to start scanning, at this point the app asks for permissions
5. The user denies permissions and the app crashes with the error posted on the original message in this issue
6. The use opens the app once again and it crashes when loading just after the Splash Screen
7. Open the app again and same as 6, it keeps crashing.

So as you see, the problem is not me not checking for permissions, is the BarcodeScanner.XF library crashing the app when, I pressume, it's calling the `GoogleVisionBarCodeScanner.iOS.Initializer.Init()` method.

**Comment by JimmyPun610** [comment]
> > > No, the camera is only used for QR Code scanning and it's on a modal page that is navigated to manually.
> > > The app cannot even get to that modal page after the permissions have been denied.
> > 
> > 
> > I suggest you check the camera permission before get into the modal page.
> 
> I think I didn't explain myself properly. The scenario is the following:
> 
> 1. Open the app for the first time. There's no camera needed at this point
> 2. There's a menu button (in my app) to go to the Scan QQ Code page, tap on that button
> 3. The app navigates to the page with the QR Code scanner
> 4. The user taps on a button to start scanning, at this point the app asks for permissions
> 5. The user denies permissions and the app crashes with the error posted on the original message in this issue
> 6. The use opens the app once again and it crashes when loading just after the Splash Screen
> 7. Open the app again and same as 6, it keeps crashing.
> 
> So as you see, the problem is not me not checking for permissions, is the BarcodeScanner.XF library crashing the app when, I pressume, it's calling the `GoogleVisionBarCodeScanner.iOS.Initializer.Init()` method.

For the first time crash, it is because the app is calling AVFoundation function without permission, which is normal case.

I will suggest the follow step as a workaround.
1. Start app, init the library
2. Check the permission when users click the button, if no permission, do not push the modal page


For your step 6 and 7, do have get any error message? and is it ok if the camera permission is granted? Since the init function does not include logic at all.

**Comment by pablo-gasparinid** [comment]
I think you are not understanding the issue, I can't ask for permission after the first time the app crashes because it doesn't make it after the splashscreen. As in, you see the loading page and the app crashes.
When the app has been just installed in the device, there's no error. The error that causes the app to crash is the one on the original post in this issue.
```
Unhandled managed exception: Could not initialize an instance of the type 'AVFoundation.AVCaptureDeviceInput': the native 'initWithDevice:error:' method returned nil.
It is possible to ignore this condition by setting ObjCRuntime.Class.ThrowOnInitFailure to false. (System.Exception)
  at Foundation.NSObject.InitializeHandle (System.IntPtr handle, System.String initSelector) [0x000a8] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/Foundation/NSObject2.cs:504 
  at AVFoundation.AVCaptureDeviceInput..ctor (AVFoundation.AVCaptureDevice device, Foundation.NSError& error) [0x00027] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/AVCaptureDeviceInput.g.cs:80 
  at GoogleVisionBarCodeScanner.UICameraPreview.Initialize (System.Boolean defaultTorchOn, System.Boolean vibrationOnDetected, System.Boolean startScanningOnCreate) [0x0009d] in <d513dc25a3de4543b7e74dac86eab609>:0 
  at GoogleVisionBarCodeScanner.UICameraPreview..ctor (System.Boolean d<…>
```

**Comment by JimmyPun610** [comment]
> I think you are not understanding the issue, I can't ask for permission after the first time the app crashes because it doesn't make it after the splashscreen. As in, you see the loading page and the app crashes.
> When the app has been just installed in the device, there's no error. The error that causes the app to crash is the one on the original post in this issue.
> 
> ```
> Unhandled managed exception: Could not initialize an instance of the type 'AVFoundation.AVCaptureDeviceInput': the native 'initWithDevice:error:' method returned nil.
> It is possible to ignore this condition by setting ObjCRuntime.Class.ThrowOnInitFailure to false. (System.Exception)
>   at Foundation.NSObject.InitializeHandle (System.IntPtr handle, System.String initSelector) [0x000a8] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/Foundation/NSObject2.cs:504 
>   at AVFoundation.AVCaptureDeviceInput..ctor (AVFoundation.AVCaptureDevice device, Foundation.NSError& error) [0x00027] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/AVCaptureDeviceInput.g.cs:80 
>   at GoogleVisionBarCodeScanner.UICameraPreview.Initialize (System.Boolean defaultTorchOn, System.Boolean vibrationOnDetected, System.Boolean startScanningOnCreate) [0x0009d] in <d513dc25a3de4543b7e74dac86eab609>:0 
>   at GoogleVisionBarCodeScanner.UICameraPreview..ctor (System.Boolean d<…>
> ```

Can you grant the permission in Settings provided by iOS and open the app again to see if the error still here?

**Comment by pablo-gasparinid** [comment]
You are right, the Init wasn't throwing the error. Somehow the CameraView was being instantiated before the page that contained it was even created. I re-created the app and reinstalled the nuget package and it now works. This can now be closed, the mystery of why it works now worries me a bit but I'll take the win.  

Thanks for the help
