### ISSUE TITLE
version 4.8.0 and above android main activity init issue and MVVM 

### ISSUE THREAD

**Issue by fkbeys** [JimmyPun610/BarcodeScanner.XF#49]
First of all, thank you for this great work.

in version 4.7 and below, for the android MainActivity ,
the  GoogleVisionBarCodeScanner.Droid.RendererInitializer.Init();  method works.
but after 4.8.0 and above, i couldnt find how to init the scanner for android. 

And how can i implement this library with MVVM?
OnDetected event doesnt support binding to MVVM.
thank you

**Comment by JimmyPun610** [comment]
Hi @fkbeys 

Thank you for your support.
Support on MonoAndroid9 is removed after version 4.8, please check the target framework of your Android project to see if you are using MonoAndroid 10 or above.

For MVVM, current design does not support it.

**Comment by sanju3005** [comment]
Any Update on MVVM binding on OnDetected? Please help
