### ISSUE TITLE
iOS: ipa file size too large

### ISSUE THREAD

**Issue by dienbien001** [JimmyPun610/BarcodeScanner.XF#50]
Hello there.
Is anyone face large ipa file size problem? After add BarcodeScanner.XF, my ipa file increase size from 12MB to 69MB, linker behavior already set to Link SDK, Solution Configuration set to Release, Solution Platform set to iPhone
When I upload to AppStore, the ipa file got rejected.
Any solution?
Thanks.

**Comment by JimmyPun610** [comment]
Hi @dienbien001 

Please provide the message from Apple for investigation.

**Comment by dienbien001** [comment]
Hi @JimmyPun610 
Thank for your fast reply.
This is the message when I use Transporter to upload ipa file:
![image](https://user-images.githubusercontent.com/21100716/103412016-c44d0100-4ba5-11eb-8ea1-ef22ffcc0f07.png)

**Comment by dienbien001** [comment]
Look like I found solution. Change minumum OS version to 9.0 fix the problem. Thank you very much.

**Comment by CodeOfDarkness** [comment]
I think changing the minimum OS version is just a workaround, isn't it?
My (installed) app grew up from 55 MB to about 200 MB after adding BarcodeScanner.XF to my project.

Is there any other solution than changing the minimum OS version to 9.0? 

Thank you mery much for your answers.

**Comment by JimmyPun610** [comment]
> I think changing the minimum OS version is just a workaround, isn't it?
> My (installed) app grew up from 55 MB to about 200 MB after adding BarcodeScanner.XF to my project.
> 
> Is there any other solution than changing the minimum OS version to 9.0?
> 
> Thank you mery much for your answers.

Hi @CodeOfDarkness ,

According to the instruction from Apple, binary over 60Mb should be iOS 9 or above.

https://help.apple.com/app-store-connect/#/dev611e0a21f

**Comment by CodeOfDarkness** [comment]
I understand that I have to use iOS 9 or above and that solves my problem when uploading. 

My app is designed for being downloaded over cellular network so I think you understand why this is a huge point for me.
Is there any possibility to get it some MB smaller?

**Comment by JimmyPun610** [comment]
Hi @CodeOfDarkness ,

I understand your concern, however the size is increased due to MLKit which is the core part of the library.

```
<PackageReference Include="Xamarin.Firebase.iOS.Core" Version="6.10.4">
		</PackageReference>
		<PackageReference Include="Xamarin.Firebase.iOS.MLKit" Version="0.21.0">
		</PackageReference>
		<PackageReference Include="Xamarin.Firebase.iOS.MLKit.Common" Version="0.21.0">
		</PackageReference>
```

Above is the binding libraries which are provided by Xamarin github that making the size increase. Not all functionalities of firebase are using in barcode scanning (Vision part only).

The size could be reduced by removing unrelated firebase libraries (https://stackoverflow.com/questions/52176739/how-to-reduce-the-package-size-of-ml-kit-ios).
However, when it comes to Xamarin, it would have a lot of work to create the correct binding library of that.

**Comment by brunonocetti** [comment]
Having the same issue. @JimmyPun610 I notice if I reference iOS.MLKit.Vision directly instead of iOS.MLKit the install size slightly decreases. I think the library don't need to reference iOS.MLKit just Vision. Still going to be a big ipa, but.. some MB less here and there helps.

**Comment by JimmyPun610** [comment]
just update 5.0.5 to referencing vision library and firebase.core only. That may reduce some ipa size
