### ISSUE TITLE
Issue with connection to PRISM EventToCommandBehavior

### ISSUE THREAD

**Issue by yevgeny-sotnikov** [JimmyPun610/BarcodeScanner.XF#54]
| found an issue with connection of CameraView.OnDetected event to PRSIM EventToCommandBehavior - now is not possible to pass BarcodeResults as parameter to command.Execute method cuz EventToCommandBehavior requires that data provided via [public property](https://github.com/PrismLibrary/Prism/blob/7b8b6c36e80ca78d484a9a0a34193e71dce3ed33/src/Forms/Prism.Forms/Behaviors/EventToCommandBehavior.cs#L227)
   
This issue very easy to fix - to change BarcodeResults to property:

`public class OnDetectedEventArg : EventArgs
    {
        public List<BarcodeResult> BarcodeResults { get; set; }

        public OnDetectedEventArg()
        {
            BarcodeResults = new List<BarcodeResult>();
        }
    }`

**Comment by yevgeny-sotnikov** [comment]
I made a fix with branch but unfortunatelly I  can't to push it :(

**Comment by JimmyPun610** [comment]
Just uploaded 5.0.2 on this.
Please update the package to see if it works

**Comment by yevgeny-sotnikov** [comment]
Problem was fixed. Thank you
