### ISSUE TITLE
iOS scan interval

### ISSUE THREAD

**Issue by brunonocetti** [JimmyPun610/BarcodeScanner.XF#57]
@JimmyPun610 is there a reason for the 1 second scan interval on iOS? In order to discard "false positives" we capture & count the scanned barcodes and then we keep the ones with the most hits. On Android this work great because it scans many times per second. But on iOS this strategy is really slow, we have to wait several seconds to have a decent barcode count.

Btw, this library is being very helpful, thank you.

**Comment by JimmyPun610** [comment]
Hi @brunonocetti 

Scan interval is set because of #12 .
I think it could be less than 1s, may be I would make it configurable

**Comment by JimmyPun610** [comment]
Just updated version 5.0.3.
ScanInterval can be set in xaml now. Default is 500ms and minimum is 100ms
