### ISSUE TITLE
SetSupportBarcodeFormat not working on iOS

### ISSUE THREAD

**Issue by brunonocetti** [JimmyPun610/BarcodeScanner.XF#59]
I'm setting the supported barcodes like this:
`GoogleVisionBarCodeScanner.Methods.SetSupportBarcodeFormat(BarcodeFormats.Ean13 | BarcodeFormats.Code39 | BarcodeFormats.Code128 | BarcodeFormats.Itf | BarcodeFormats.Pdf417);`

On Android only those types of barcodes are read. But on iOS QR codes are also registered. Actually other barcodes types also get registered. Like Data matrix, ISBN for example. So my guess is that on iOS `SetSupportBarcodeFormat` is not having effect.

I was able to reproduce this issue on the sample app (adding SetSupportBarcodeFormat of course).

Tested on: _iPhone XR 14.4.2_, _iPhone 12 Pro 14.4.2_ & _iPhone 6s Plus 13.7_

**Comment by JimmyPun610** [comment]
Hi @brunonocetti 

Thank you for bug reporting.
I have updated version 5.0.4 to fix this. Please have a try on that.
