### ISSUE TITLE
No Camera preview on android 10, with target framework Android 9.

### ISSUE THREAD

**Issue by Tims159** [JimmyPun610/BarcodeScanner.XF#6]
The camera view can be seen on Android N, but on Android 10 , view doesn't appear but QR code is scanned.

**Comment by JimmyPun610** [comment]
Will investigate it once xamarin android 10 officially release.

**Comment by kberawala** [comment]
> Will investigate it once xamarin android 10 officially release.

any update on this ? any ETA?

**Comment by JimmyPun610** [comment]
> > Will investigate it once xamarin android 10 officially release.
> 
> any update on this ? any ETA?

I tested on simulator and it has no problem to show the simulated camera output. But I do not have real device in Android 10.

**Comment by Tims159** [comment]
Working fine on pixel 2 xl with Android 10.

Closing issue.
