### ISSUE TITLE
Android 6.0 Marshmallow support

### ISSUE THREAD

**Issue by TomVHRebel** [JimmyPun610/BarcodeScanner.XF#62]
Does BarcodeScanner.XF support android version 6.0? We have installed BarcodeScanner.XF v5.0.2

**Comment by JimmyPun610** [comment]
Hi @TomVHRebel ,

I did not test on Android 6 before so I could not ensure it is working perfectly in Android 6.

**Comment by TomVHRebel** [comment]
Thank for the response @JimmyPun610, 

Will BarcodeScanner.XF support Android version 6.0 in the future?

**Comment by JimmyPun610** [comment]
> Thank for the response @JimmyPun610,
> 
> Will BarcodeScanner.XF support Android version 6.0 in the future?

I don't think so, that was about 5 years ago.
I suggest you try it on an Android 6 device to see if current version is supporting it if you are expecting users with Android 6.

**Comment by TomVHRebel** [comment]
> 
> 
> > Thank for the response @JimmyPun610,
> > Will BarcodeScanner.XF support Android version 6.0 in the future?
> 
> I don't think so, that was about 5 years ago.
> I suggest you try it on an Android 6 device to see if current version is supporting it if you are expecting users with Android 6.

I tried it on a a Android 6 device and the visual studio android 6 emulator. The Camera shows but it doesn't respond to a QR-code.

**Comment by JimmyPun610** [comment]
Is that only happen in Android 6? I wonder if you have set the detecting format or not.

**Comment by TomVHRebel** [comment]
> 
> 
> Is that only happen in Android 6? I wonder if you have set the detecting format or not.
> Or you may try to download the sample app in debug mode to see how is breaking the functionality

I tested it a bit more and found out that version 7 and 8 also don't work. I am trying run your sample app but I ran into some problems.

**Comment by danrus** [comment]
I can confirm that the library works with Android 6, 7, 9 and 11 (I do not have test devices with 8 and 10 but should not be any problems there also). Tested for QR-Codes and compiled with the target framework Android 10.

**Comment by TomVHRebel** [comment]
> 
> 
> I can confirm that the library works with Android 6, 7, 9 and 11 (I do not have test devices with 8 and 10 but should not be any problems there also). Tested for QR-Codes and compiled with the target framework Android 10.

Did you test with a real phone or a emulator? Maybe some version aren't working because I am using a emulator?

**Comment by danrus** [comment]
> > I can confirm that the library works with Android 6, 7, 9 and 11 (I do not have test devices with 8 and 10 but should not be any problems there also). Tested for QR-Codes and compiled with the target framework Android 10.
> 
> Did you test with a real phone or a emulator? Maybe some version aren't working because I am using a emulator?

Tested with real devices. I am not sure how this test would work on an emulator...you do need the camera for it...

**Comment by JimmyPun610** [comment]
Thank you @danrus .

Hi @TomVHRebel ,

I suggest you try it on the real device. If there is any problem occur,
Please provide more information and the error log for your testing in older Android version

**Comment by TomVHRebel** [comment]
> 
> 
> > > I can confirm that the library works with Android 6, 7, 9 and 11 (I do not have test devices with 8 and 10 but should not be any problems there also). Tested for QR-Codes and compiled with the target framework Android 10.
> > 
> > 
> > Did you test with a real phone or a emulator? Maybe some version aren't working because I am using a emulator?
> 
> Tested with real devices. I am not sure how this test would work on an emulator...you do need the camera for it...

I used the webcam of my laptop to test it. I hope to test it soon on some older real devices. Thanks @danrus and @JimmyPun610  for the response.
