### ISSUE TITLE
MultiDetector Example

### ISSUE THREAD

**Issue by AdziGin** [JimmyPun610/BarcodeScanner.XF#64]
Hi there

   very nice example and up to date with the new xamarin forms. 

any chance there is an example of using the multidetector.builder for multiple: barcodes,words or faces ?
where a multidetector is basically detecting whatever displayed and saving on the start scan button. 

  have been trying to implement something like this from the page3.xaml example but there is some difficulty in implementing the different TrackerFactory class with the multi detector. 

Thanks

**Comment by JimmyPun610** [comment]
Sorry I think this is a little bit out of scope
