### ISSUE TITLE
Rotation of CameraView wrong way on iOS in landscape-mode

### ISSUE THREAD

**Issue by ramonB1996** [JimmyPun610/BarcodeScanner.XF#66]
First of all, thanks for this library!

I found a small issue with landscape-mode on iOS 14+, where the `CameraView` gets rotated the wrong way around.

It is related to this closed issue: https://github.com/JimmyPun610/BarcodeScanner.XF/issues/55
It also was fixed for older iOS versions I believe, because of this commit: https://github.com/JimmyPun610/BarcodeScanner.XF/commit/3d5c389d945b878aa63dd4976515894a9195dd3d

The problem is with the code in `UICameraPreview.setPreviewOrientation()` starting on `line 69`.

I do not have enough time to create a PR at the moment, if someone is willing to do this, feel free! :)

**Comment by JimmyPun610** [comment]
Hi @ramonB1996 ,

Thank you for reporting the issue, I have upload 5.0.6 for the fix, please see if it is ok

**Comment by ramonB1996** [comment]
Hi @JimmyPun610,

Thank you for the quick response! Your changes work perfectly on my iPhone XR with iOS 14.6 (newest version currently). 

I hope it will still work for older versions, but I can not test that :)
