### ISSUE TITLE
MTOUCH : error MT5210: Native linking failed, undefined symbol on IOS

### ISSUE THREAD

**Issue by technololy** [JimmyPun610/BarcodeScanner.XF#69]
Thank you for this amazing library.

When added to XF 5.0.0.2012 in VS Mac 8.10.2 the project refused o build with the error in the subject.

see more below

MTOUCH : error MT5210: Native linking failed, undefined symbol: _GTMFetcherApplicationIdentifier. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _GTMFetcherSystemVersionString. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _GTMSessionFetcherAssertValidSelector. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _GULIsLoggableLevel. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _GULLogBasic. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _GULLogError. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _GULLogInfo. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _GULLogWarning. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _GULSetLoggerLevel. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FIRApp. The symbol '_OBJC_CLASS_$_FIRApp' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FIRAppAssociationRegistration. The symbol '_OBJC_CLASS_$_FIRAppAssociationRegistration' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FIRComponent. The symbol '_OBJC_CLASS_$_FIRComponent' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FIRComponentType. The symbol '_OBJC_CLASS_$_FIRComponentType' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FIRInstallations. The symbol '_OBJC_CLASS_$_FIRInstallations' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FIRRemoteConfig. The symbol '_OBJC_CLASS_$_FIRRemoteConfig' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GPBCodedOutputStream. The symbol '_OBJC_CLASS_$_GPBCodedOutputStream' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GPBDescriptor. The symbol '_OBJC_CLASS_$_GPBDescriptor' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GPBEnumArray. The symbol '_OBJC_CLASS_$_GPBEnumArray' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GPBEnumDescriptor. The symbol '_OBJC_CLASS_$_GPBEnumDescriptor' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GPBExtensionDescriptor. The symbol '_OBJC_CLASS_$_GPBExtensionDescriptor' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GPBExtensionRegistry. The symbol '_OBJC_CLASS_$_GPBExtensionRegistry' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GPBFileDescriptor. The symbol '_OBJC_CLASS_$_GPBFileDescriptor' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GPBInt32Array. The symbol '_OBJC_CLASS_$_GPBInt32Array' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GPBMessage. The symbol '_OBJC_CLASS_$_GPBMessage' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GPBRootObject. The symbol '_OBJC_CLASS_$_GPBRootObject' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GTLRVisionQuery_ImagesAnnotate. The symbol '_OBJC_CLASS_$_GTLRVisionQuery_ImagesAnnotate' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GTLRVisionService. The symbol '_OBJC_CLASS_$_GTLRVisionService' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GTLRVision_AnnotateImageRequest. The symbol '_OBJC_CLASS_$_GTLRVision_AnnotateImageRequest' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GTLRVision_BatchAnnotateImagesRequest. The symbol '_OBJC_CLASS_$_GTLRVision_BatchAnnotateImagesRequest' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GTLRVision_DetectedBreak. The symbol '_OBJC_CLASS_$_GTLRVision_DetectedBreak' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GTLRVision_Feature. The symbol '_OBJC_CLASS_$_GTLRVision_Feature' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GTLRVision_Image. The symbol '_OBJC_CLASS_$_GTLRVision_Image' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GTLRVision_ImageContext. The symbol '_OBJC_CLASS_$_GTLRVision_ImageContext' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GTLRVision_LatLng. The symbol '_OBJC_CLASS_$_GTLRVision_LatLng' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GTMLogMininumLevelFilter. The symbol '_OBJC_CLASS_$_GTMLogMininumLevelFilter' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GTMLogger. The symbol '_OBJC_CLASS_$_GTMLogger' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GTMSessionCookieStorage. The symbol '_OBJC_CLASS_$_GTMSessionCookieStorage' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GTMSessionFetcher. The symbol '_OBJC_CLASS_$_GTMSessionFetcher' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GTMSessionFetcherService. The symbol '_OBJC_CLASS_$_GTMSessionFetcherService' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GULAppDelegateSwizzler. The symbol '_OBJC_CLASS_$_GULAppDelegateSwizzler' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GULAppEnvironmentUtil. The symbol '_OBJC_CLASS_$_GULAppEnvironmentUtil' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GULMutableDictionary. The symbol '_OBJC_CLASS_$_GULMutableDictionary' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GULNetwork. The symbol '_OBJC_CLASS_$_GULNetwork' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GULSwizzler. The symbol '_OBJC_CLASS_$_GULSwizzler' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GULUserDefaults. The symbol '_OBJC_CLASS_$_GULUserDefaults' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: TFLInterpreter. The symbol '_OBJC_CLASS_$_TFLInterpreter' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _OBJC_METACLASS_$_GPBMessage. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _OBJC_METACLASS_$_GPBRootObject. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _OBJC_METACLASS_$_GTMLogger. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _TFLVersion. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _kFIRAppDeleteNotification. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _kFIRAppNameKey. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _kFIRDefaultAppName. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _kFIRLoggerMLKit. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGTLRVision_Block_BlockType_Barcode. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGTLRVision_Block_BlockType_Picture. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGTLRVision_Block_BlockType_Ruler. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGTLRVision_Block_BlockType_Table. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGTLRVision_Block_BlockType_Text. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGTLRVision_DetectedBreak_Type_EolSureSpace. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGTLRVision_DetectedBreak_Type_Hyphen. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGTLRVision_DetectedBreak_Type_LineBreak. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGTLRVision_DetectedBreak_Type_Space. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGTLRVision_DetectedBreak_Type_SureSpace. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGTLRVision_Feature_Type_DocumentTextDetection. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGTLRVision_Feature_Type_LabelDetection. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGTLRVision_Feature_Type_LandmarkDetection. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGTLRVision_Feature_Type_TextDetection. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGTMSessionFetcherStatusDomain. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGULNetworkHTTPStatusCodeCannotAcceptTraffic. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGULNetworkHTTPStatusCodeNotFound. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGULNetworkHTTPStatusCodeNotModified. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGULNetworkHTTPStatusCodeUnavailable. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGULNetworkHTTPStatusNoContent. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGULNetworkHTTPStatusOK. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_decode. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_decode_varint. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_encode. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_encode_string. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_encode_submessage. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_encode_tag_for_field. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_encode_varint. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_istream_from_buffer. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_ostream_from_buffer. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_read. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
    		
    MTOUCH : warning MT5215: References to 'System' might require additional -framework=XXX or -lXXX instructions to the native linker
    		
    MTOUCH : warning MT5215: References to 'System.Net.Security' might require additional -framework=XXX or -lXXX instructions to the native linker
    		
    MTOUCH : warning MT5215: References to 'Kernel32' might require additional -framework=XXX or -lXXX instructions to the native linker
    		
    MTOUCH : warning MT5215: References to 'libEGL' might require additional -framework=XXX or -lXXX instructions to the native linker
    		
    MTOUCH : error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: -ObjC -lc++ -lsqlite3 -lz -ObjC -lc++ -lsqlite3 -lz -lc++ -ObjC -ObjC -lc++ -ObjC -lc++ -ObjC -lc++ -ObjC -lc++ -ObjC -lc++ -ObjC -lc++ -ObjC -ObjC -lc++ -ObjC -lc++ -ObjC -lc++ -lz -ObjC -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker "/Users/ololadeoyebanji/Projects/SterlingMobile/SterlingMobile.iOS/obj/iPhoneSimulator/Debug/device-builds/iphone 8-14.4/Entitlements.xcent"

**Comment by JimmyPun610** [comment]
Hi @technololy,

I have tried the same config as you and it seems alright.
Did your iOS project set to Link framework SDK only and ARM64 only?

I also updated the package to Xamarin Form 5.0.0.2012 in version 5.0.8

**Comment by dzeping96** [comment]
Hi @JimmyPun610,

I encounter the same issue as @technololy, but I only have this line of error, 
`MTOUCH : error MT5210: Native linking failed, undefined symbol: _kFIRLoggerMLKit. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.`

I using the BarcodeScanner.XF 6.2.2-pre which using your custom build iOS MLKit library and removed the deprecated Xamarin.Firebase.iOS.MLKit and Xamarin.Firebase.iOS.MLKit.Common which I use previously, but the error still exist, do you have any idea regarding this? Appreciate your helps!

I did set my iOS project to Link framework SDK only and ARM64 only as well.

For your reference, my current NuGet version:

- Xamarin.Forms 5.0.0.2401
- BarcodeScanner.XF 6.2.2-pre
- Xamarin.Build.Download 0.11.2
- Xamarin.Essentials 1.7.3
- Xamarin.Google.iOS.SignIn 5.0.2.3

**Comment by omatrot** [comment]
I have the exact sae problem as @dzeping96.
Please fix this issue as it prevents my app to be published to the store.
Thanks in advance.

**Comment by technololy** [comment]
@JimmyPun610 thanks. i remember it worked for me after some house cleaning. thank you for this amazing library
