### ISSUE TITLE
Xamarin.Android ML Kit Vision Barcode Scan.

### ISSUE THREAD

**Issue by pulmuone** [JimmyPun610/BarcodeScanner.XF#7]
Can I scan barcodes using ML Kit on Xamarin.Android?
It seems possible with Nuget "Xamarin.Firebase.ML.Vision".
Can I do Java source using the MK Kit with Xamarin?
https://github.com/firebase/quickstart-android/tree/master/mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/java

**Comment by JimmyPun610** [comment]
I think yes.
Google Vision is part of ML Kit.
Please feel free to contribute
