### ISSUE TITLE
Android: If we change the barcode format from QR to anything else it does not take effect

### ISSUE THREAD

**Issue by PinchofLogic** [JimmyPun610/BarcodeScanner.XF#74]
It seems like if we change or add other barcode formats via Page1.xaml.cs it does not take effect and the sample app continue to only scan QR codes. 

I noticed, in the below two files:
1) GoogleVisionBarCodeScanner>Android>Renderer>CameraViewRenderer.cs (line 184)
2) GoogleVisionBarCodeScanner>Android>Methods.cs (line 118)

QRCode format is hardcoded and it does not reflect any changes done in the Page1.xaml.cs. Hence the app continues to only scan the QR codes.

Once changes are made to the above files, it starts to work.

**Comment by JimmyPun610** [comment]
Hi @PinchofLogic 

Thank you for pointing out.
I have just uploaded 6.0.0.2-pre to nuget for this bug fix.
