### ISSUE TITLE
library compatibility

### ISSUE THREAD

**Issue by porfire** [JimmyPun610/BarcodeScanner.XF#76]
Hi guys, I got this error on my solution when I try to integrate the QR code functionality into my project

Error NU1107	Version conflict detected for Xamarin.AndroidX.Lifecycle.LiveData. Install/reference Xamarin.AndroidX.Lifecycle.LiveData 2.3.1.1 directly to project NFLPCApp.Android to resolve this issue. 
 NFLPCApp.Android -> NFLPCApp -> BarcodeScanner.XF 6.0.0.2-pre -> Xamarin.AndroidX.Lifecycle.LiveData (>= 2.3.1.1) 
 NFLPCApp.Android -> Xamarin.Forms 5.0.0.2083 -> Xamarin.AndroidX.Lifecycle.LiveData (>= 2.2.0.4 && < 2.3.0).	

can you help me, thanks

**Comment by stepkillah** [comment]
@porfire as an error saying `Install/reference Xamarin.AndroidX.Lifecycle.LiveData 2.3.1.1 directly to project NFLPCApp.Android to resolve this issue.`. That's exactly what's needs to be done, you need to install Xamarin.AndroidX.Lifecycle.LiveData 2.3.1.1 to your Android project
