### ISSUE TITLE
Error when building to IOS

### ISSUE THREAD

**Issue by metazul** [JimmyPun610/BarcodeScanner.XF#84]
When building to IOS I receive the following error:

C:\Users\MyName\.nuget\packages\xamarin.build.download\0.10.0\buildTransitive\Xamarin.Build.Download.targets(52,3): error : Object reference not set to an instance of an object

I tried the SampleApp code and jfversluis/XFAlternativeBarcodeScanningSample (Gerald sample) and got this error.  Even in a blank project, if I add the nuget BarcodeScanner.XF, after that the build fail. Android build succeeded. The build error just happen on IOS.

I am using Visual Studio 2019 (Windows) version 16.11.3 (I tried 16.10.4 too). Xamarin 16.11.000.175. Xamarin IOS 14.20.0.25. Xcode 12.5.1. macOS BigSur 11.6. Xamarin Forms 5.0.0.2012 (tried other versions too). BarcodeScanner.XF 5.0.9 (tried 6.1.0-pre too).

Edited:
Now I noticed that when I add this nuget (BarcodeScanner.XF) to my solution the error appears immediatily on "Error List" view (Description: Object reference not set to an instance of an object; File: Xamarin.Build.Download.targets; Line 52). And I can't see  BarcodeScanner in my IOS project references (but I can see in my Android Project). 
I am thinking the problem is it dependency, because I try to add the nuget package Xamarin.Firebase.IOS.Core and the same error happen. But I've tried everything to fix it and nothing works.

I would really appreciate some help.

**Comment by JimmyPun610** [comment]
Did you try to install 
https://www.nuget.org/packages/Xamarin.Build.Download/0.4.5
to your project?

**Comment by metazul** [comment]
> Did you try to install
> https://www.nuget.org/packages/Xamarin.Build.Download/0.4.5
> to your project?

Yes, I did. 

I've been working with Xamarin since 2016. Mainly in the beginning there were many bugs, but I always managed to solve them. It's the first time I see a problem that, after researching a lot on the internet, that I can't solve and that doesn't seem to happen with many colleagues. 
I've also tested it on two different Windows computers and the only thing in common is my Mac Mini, but I don't think it would cause this problem.
Probably BarcodeScanner.XF is not the root cause of the problem, but I appreciate the help of any colleague with any ideas.

**Comment by JimmyPun610** [comment]
> > Did you try to install
> > https://www.nuget.org/packages/Xamarin.Build.Download/0.4.5
> > to your project?
> 
> Yes, I did.
> 
> I've been working with Xamarin since 2016. Mainly in the beginning there were many bugs, but I always managed to solve them. It's the first time I see a problem that, after researching a lot on the internet, that I can't solve and that doesn't seem to happen with many colleagues.
> I've also tested it on two different Windows computers and the only thing in common is my Mac Mini, but I don't think it would cause this problem.
> Probably BarcodeScanner.XF is not the root cause of the problem, but I appreciate the help of any colleague with any ideas.

For me, there are 3 ways for me to try
1.
```
1. close my visual studio
2. remove all bin/obj folder in the projects
3. open the project and rebuild
```
2. you may also try to remove nuget cache
```
https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders

It will take time to download all the package again.
```

3.
```
 repair the external hdd if your project is located in there
```

**Comment by metazul** [comment]
Unfortunately I've tried all of them (except 3 for not using external hard drive) and none of them worked.

Thank you so much @JimmyPun610 for the tips.

I'll keep trying and if new ideas come up, I appreciate it.
