### ISSUE TITLE
Source code of previous releases

### ISSUE THREAD

**Issue by bachthsn** [JimmyPun610/BarcodeScanner.XF#86]
Hello,

is it possible to download the source code for the latest stable release? I am aksing because of a quite special problem that I have... I am working on a Fire Tablet (Amazon), which does not have the Google Play Store onboard (by default at least). However, the Nuget packages of BarcodeScanner.XF somehow need these for the recognition of QR codes. My project works fine with the Nuget packages and I see the camera output on the display, but the recognition event does not fire. Instead, there is a constant stream of error messages in in the Output window of Visual Studio. 

When I compile the source code and run the sample app on the same tablet, it works indeed. So my question is: Can I download the source code of previous releases? 

Thanks a lot,
Sven

**Comment by davidbuckleyni** [comment]
If u click change branch even on the ios app the old versions are listed their

**Comment by bachthsn** [comment]
Hi davidbuckleyni,

thanks a lot, I feel stupid now... I am new to GitHub :-) 

Cheers,
Sven
